language: csharp
dist: trusty
mono: none 
dotnet: 2.0.0
script:
 - npm i -g npm
 - npm install -g webpack  
 - dotnet restore SimpleCmsCore.sln
 - cd /src/Hosts/SimpleCms.App/
 - npm install
 - dotnet run build
# - cd wwwroot/react-app/

# - npm install && npm run build

#  env:
#   global:
#     - "FTP_USER=user"
#     - "FTP_PASSWORD=password"
# after_success:
#     "curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD ftp://sitename.com/directory/myfile"